# Generated by Django 4.1.4 on 2023-01-17 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_person_delete_amodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='person',
            new_name='Amodel',
        ),
    ]
